CREATE OR REPLACE FUNCTION SCOTT.topnsal(p_n NUMBER) RETURN NUMBER IS
    l_sum NUMBER(10,2);
BEGIN
    SELECT SUM(sal) INTO l_sum FROM 
        (   SELECT e.sal FROM SCOTT.emp e ORDER BY e.sal DESC 
            OFFSET 0 ROWS FETCH NEXT p_n ROWS ONLY );
    RETURN l_sum;        
END topnsal;

SELECT * FROM ALL_OBJECTS 
WHERE OWNER = 'SCOTT' AND OBJECT_TYPE IN ('FUNCTION', 'PROCEDURE');
/
BEGIN
    SCOTT.topnsal_caller;
END;
/
ALTER PROCEDURE SCOTT.topnsal_caller COMPILE;
/
SELECT NAME, PLSQL_OPTIMIZE_LEVEL, PLSQL_DEBUG FROM ALL_PLSQL_OBJECT_SETTINGS WHERE OWNER = 'SCOTT';
/
ALTER FUNCTION SCOTT.topnsal COMPILE DEBUG; --bekapcsolja
ALTER PROCEDURE SCOTT.topnsal_caller COMPILE PLSQL_OPTIMIZE_LEVEL=1; --ez is bekapcsolja

