CREATE TABLE OE.order_items_tmp
(	
	ORDER_ID 		NUMBER(12,0) NULL, 
	LINE_ITEM_ID 	NUMBER(3,0)  NULL, 
	PRODUCT_ID 		NUMBER(6,0)  NULL, 
	UNIT_PRICE 		NUMBER(8,2)  NULL, 
	QUANTITY 		NUMBER(8,0)  NULL )
PARTITION BY HASH (ORDER_ID) PARTITIONS 4;
/
BEGIN
  DBMS_REDEFINITION.START_REDEF_TABLE('OE', 'ORDER_ITEMS', 'ORDER_ITEMS_TMP');
END;
/
DECLARE
  num_errors NUMBER;
BEGIN
  DBMS_REDEFINITION.COPY_TABLE_DEPENDENTS('OE', 'ORDER_ITEMS', 'ORDER_ITEMS_TMP', copy_indexes => 0, num_errors => num_errors);
  DBMS_OUTPUT.PUT_LINE(num_errors);
END;  
/
--ha hiba történt és nem tudjuk kijavítani:
BEGIN
  DBMS_REDEFINITION.ABORT_REDEF_TABLE('OE', 'ORDER_ITEMS', 'ORDER_ITEMS_TMP');
END;
/
BEGIN
  DBMS_REDEFINITION.FINISH_REDEF_TABLE('OE', 'ORDER_ITEMS', 'ORDER_ITEMS_TMP');
END;
/
BEGIN
  DBMS_STATS.GATHER_TABLE_STATS('OE', 'ORDER_ITEMS');
END;
/
SELECT * FROM DBA_TAB_PARTITIONS WHERE TABLE_OWNER = 'OE';
/
DROP TABLE OE.order_items_tmp;
--indexek és NOT NULL megszorítások ellenõrzésére szükség lehet

--Oracle 12c R2-tõl egyszerûbb megoldás:
ALTER TABLE OE.order_items MODIFY 
PARTITION BY HASH (order_id) PARTITIONS 4;
